# Generated by Django 5.1.5 on 2025-01-28 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address', max_length=255, unique=True)),
                ('ton_wallet_address', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has verified their email address')),
                ('is_onboarded', models.BooleanField(default=False, help_text='Whether the user has completed the onboarding process')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], help_text='Enter your gender', max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter your date of birth', null=True)),
                ('location', models.CharField(blank=True, help_text='Enter your location', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, help_text='Write a short bio about yourself', max_length=500, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_pictures/')),
                ('country_code', models.CharField(blank=True, help_text='Enter your country code', max_length=5, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter your phone number', max_length=15, null=True)),
                ('language_preference', models.CharField(blank=True, help_text='Enter your preferred language', max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, help_text='Enter your timezone', max_length=50, null=True)),
                ('user', models.OneToOneField(help_text='Select a user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'Users Profiles',
            },
        ),
    ]
